name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build npm package
        run: bun run build:npm
      - run: bun test
      
  build-test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - name: Build standalone executable
        run: bun build --compile --external blessed --outfile=backlog-test${{ matrix.os == 'windows-latest' && '.exe' || '' }} src/cli.ts
      - name: Test executable (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          ./backlog-test --version
          ./backlog-test --help
      - name: Test executable (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          .\backlog-test.exe --version
          .\backlog-test.exe --help
